[aws]
format = "\n[$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)"

[directory]
format = "ğŸ“ [$path]($style)[$read_only]($read_only_style) "
truncation_length = 10
truncation_symbol = "â€¦"

[hostname]
format = "ğŸ’» [$hostname]($style) "
ssh_only = false

[nix_shell]
symbol = "â„ "

[time]
disabled = false
format = "ğŸ•‘ [$time]($style) "

[username]
format = "ğŸ‘¤ [$user]($style) "
show_always = true
